# Use the official Node.js image.
FROM node:20

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json to the working directory.
COPY ./server/package*.json ./

# Install the application dependencies.
RUN npm install

# Copy the rest of your application code.
COPY ./server .

# Expose the port the app runs on.
EXPOSE 5000

# Command to run the application.
CMD ["node", "src/server.js"]
