# Use the official Node.js image.
FROM node:20

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json to the working directory.
COPY package*.json ./server

# Install the application dependencies.
RUN npm install

# Copy the rest of your application code.
COPY . .

# Command to run the scraping service.
CMD ["node", "src/scraper.js"]
