FROM node:20-alpine

WORKDIR /app/server

COPY ./server/package*.json ./

RUN npm install --production && npm cache clean --force

COPY ./server ./

RUN mkdir -p /app/logs

RUN apk add --no-cache supervisor

COPY ./server/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 5000

CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
