version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - VISION_AUTH_JSON=${VISION_AUTH_JSON}
    volumes:
      - ./server:/app
    command: bash -c "node src/server.js && node src/scraper.js && node src/oldOffersCollector.js"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider

