version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - VISION_AUTH_JSON="./mythic-plexus-425612-j3-59f1eac834b5.json"
    volumes:
      - .:/app # Mount current directory to /app in the container
    depends_on:
      - mongo # Ensure MongoDB is started before the web app

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    environment:
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/app # Mount current directory to /app in the container
    depends_on:
      - mongo # Ensure MongoDB is started before the scraper

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
